services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./TechXchange.sql:/docker-entrypoint-initdb.d/TechXchange.sql
      - postgres_data:/var/lib/postgresql/data
volumes:
  redis_data:
  postgres_data:
