services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "5433:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techXchange
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./techXchange.sql:/docker-entrypoint-initdb.d/techXchange.sql
      - mysql_data:/var/lib/mysql/data
volumes:
  redis_data:
  mysql_data:
